title: 梁青昆
owner: 梁青昆
email:
description: ""
baseurl: "/blog"
url: "https://qleong.com" # the base hostname & protocol for your site, e.g. http://example.com
language: en
twitter_username:
github_username:
disqus_username:
# Build settings
markdown: kramdown
theme: minima
github: [metadata]

permalink: /:year/:month/:day/:title/

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->

collections:
  books:
    output: true
